class AddCoachesData < ActiveRecord::Migration
  def change
  	stirapelle = Coach.new(:name => "Steven Tirapelle", :position => "Head Coach", :ref => "stirapelle")
    stirapelle.info = "Coach Tirapelle is in his 31st year of coaching and 17th year as the head coach of the Cougars. His coaching tenure began in 1983 at Hiram Johnson High School in Sacramento, CA. In 30 years as a head coach, Coach Tirapelle has coached 83 state medalists and 19 state champions, 76 of those placewinners and 18 champions coming at Clovis High. In his 16 years with the Cougars, Coach Tirapelle has lead the team to 10 Valley Championships, 13 'Top 5' State Finishes, and State Championships in 2003, 2008, 2011, 2012, and 2013. The most recent State Championship in 2013 is the eleventh in Clovis history and the 3rd time the program has won back-to-back-to-back titles. Clovis' 11 State Championships are the all-time best for any school in California. Coach Tirapelle is widely regarded as one of the premier coaches in the state, most notably for leading his three sons to 8 state titles and 9 finals appearances in 12 years, also tops in the state for a single family. His three sons were all scholarship athletes at the University of Illinois. Coach Tirapelle wrestled at Ponderosa High School in Placerville, CA and later at Humboldt State University where he became an NCAA Division II All-American. His wife is Jayne. His sons are Adam, Alex, & Troy and his daughter, Brooke."
  	stirapelle.save(:validate => false)

  	bholscher = Coach.new(:name => "Ben Holscher", :position => "Assistant Head Coach", :ref => "bholscher")
    bholscher.info = "Coach Ben Holscher rejoins the Cougars for his 8th year and his 10th year of coaching at the high school level after starting in the college ranks. Prior to coming on board with the Clovis staff, Ben was a volunteer assistant coach at Chadron State University, the University of Nebraska, and Fresno State University . He's also been very involved with coaching at the club/youth level with experience at the Competitive Edge Wrestling Academy, the Bulldog/Sunkist Kids Wresting Academy, and as an assistant at Clark Intermediate in addition to his year-round involvement with the high school team. As an interim head coach of the 2009 Clovis squad, Ben lead the team to a league and section championship, as well as a 4th place state finish. Ben has been an integral part of the program's success and has been named Associate Head Coach starting in the 2013-2014 season.Ben was a state runner-up in his home state of Nebraska at Ogallala High School . He did his collegiate wrestling at Chadron State University where he was a 2x NCAA Division II National Qualifier and a 3x Academic All-American. Coach Holscher brings enthusiasm and tireless work ethic to the program as he was voted the Most Dedicated Wrestler in all four of his collegiate years. Ben is married to wife, Amber, and has a son, Luke."
  	bholscher.save(:validate => false)

  	atirapelle = Coach.new(:name => "Adam Tirapelle", :position => "Assistant Coach", :ref => "atirapelle")
    atirapelle.info = "Adam Tirapelle is in his 12th year of coaching and 10th at the high school level with the Cougars. After coaching 2 years at the University of Illinois as a graduate assistant, Adam moved back to Fresno in 2005 and began coaching with his father at Clovis. In 9 years with the Cougars, Adam has implemented several programs and training regimens to mimic the Division I collegiate experience and improve the program at all levels. The Winner's Circle program, founded in 2005, is unique at the high school level and has become a staple of the Clovis Wrestling off-season training regimen. Since the inception of the Winner’s Circle, in the last 8 years the program has turned out 85 state qualifiers, 50 state medals, 7 state champions, 4 team state championships, and 7 consecutive Top 5 finishes. The son of Coach Tirapelle and eldest of the Tirapelle boys, Adam was a 2x California State Champion and a 3x Division I All-American at the University of Illinois, winning the NCAA Championship in 2001. Adam was also the Athlete-Of-The-Year for Illinois in 2001 and currently is 2nd on the all-time list for both wins and pins in a career. He possesses both an undergraduate degree in Kinesiology and Master's of Business Administration (MBA) in Finance from Illinois. He did his high school wrestling at Hiram Johnson High School in Sacramento, CA and later Buchanan High School. Adam is married to wife, Kim, and has two sons, Dylan and Zachary."
  	atirapelle.save(:validate => false)

  	psamhammer = Coach.new(:name => "Pete Samhammer", :position => "Assistant Coach", :ref => "psamhammer")
    psamhammer.info = "Coach Pete Samhammer begins his 33rd year in the coaching ranks, and his 13th with the Clovis HS Cougars. Pete has coached in three different Sections (San Diego, North, and Central), winning Championships in each, as well as State Championships at both the High School and Junior College levels. Pete has coached on three State Championship teams (83’, 85’, 88’) at Palomar Junior College, four with the Cougars in 2003, 2011, 2012, and 2013, and has coached on sixteen teams that have finished in the top three at the State Tournament. Coach Samhammer did his college wrestling at Palomar Junior College and Chico State University, and his high school wrestling at Vista High School. He has three children, Brian, Michele, and Peter, and two grandchildren, Sierra and Morgan. When Pete is away from wrestling he loves to ride his bicycle and work in his backyard."
  	psamhammer.save(:validate => false)

  	cwalbeck = Coach.new(:name => "Clint Walbeck", :position => "Assistant Coach", :ref => "cwalbeck")
    cwalbeck.info = "Clint Wallbeck begins his 7th season coaching with the Cougars. A 2000 graduate of Clovis high school, Clint is considered one of the greatest upper-weight wrestlers in Cougar history, winning a State Championship at 215lbs as a junior, and adding a runner-up finish as a senior. As a collegian, Clint was a two-time NCAA qualifier at heavyweight while competing for Fresno State. Clint is employed as a fireman for the City of Fresno. He and his wife, Erin, are proud parents of their first child, Wyatt."
  	cwalbeck.save(:validate => false)

  	elegarreta = Coach.new(:name => "Eric LeGarreta", :position => "Assistant Coach", :ref => "elegarreta")
    elegarreta.info = "Coach LeGarreta is in his 13th season with the Cougar coaching staff and his 18th year of coaching overall. Previously he spent 3 years at Sanger High School and 2 years at Fresno City Community College before joining the staff in 2001. As a coach, Eric was part of all five State Championship Clovis Teams from 2003 through 2013, spending much of his time on an individual basis with the middle and upper weights. In wrestling, he placed 6th in the California State Championships and was a Valley Champion both as an individual and as a team, being part of the first small school ever to win the section title. Eric wrestled at Selma High School followed by Golden West College, Fresno City Community College, and Fresno State University where he was a starter at 118lbs. Eric has a son, Jude, and a daughter, Addison."
  	elegarreta.save(:validate => false)

  	smoore = Coach.new(:name => "Scott Moore", :position => "Assistant Coach", :ref => "smoore")
    smoore.info = 'Coach Scott Moore joins the Cougar staff for his 17th year of coaching, all of those done at Clovis High School. He is one of the longest tenured staff members as his coaching career began as just "rolling around" with the Clovis upper weight wrestlers while a wrestler himself at Fresno State in 1978. Since that time, Scott has enjoyed years of coaching including the privilege of watching his son, Marcus, go through the Cougar program as well as being a part of all five State Championship teams under Coach Tirapelle. Scott brings invaluable experience to the program and individually works with the upper weight wrestlers on the squad. Scott did his collegiate wrestling at Fresno State where he was a PCAA Champion. Before that, he was a 2x Junior College State Medalist as well as a Southern Section Champion for Granite Hills High School. Scott is married to wife Lauri and with two adult children: Marcus, a former wrestler and football player for Clovis High, and Brooke, a former standout volleyball player for Clovis.'
  	smoore.save(:validate => false)

  	ecastillo = Coach.new(:name => "Eddie Castillo", :position => "Assistant Coach", :ref => "ecastillo")
    ecastillo.info = ""
  	ecastillo.save(:validate => false)
  end
end
